'use strict';
 Alexa = require('alexa-sdk');

var APP_ID = undefined; //OPTIONAL: replace with "amzn1.echo-sdk-ams.app.[your-unique-value-here]";
var SKILL_NAME = 'Random Facts';

/**
 * Array containing random facts.
 */
var FACTS = [
  'The inner core of the candle flame is light blue, with a temperature of around 1670 K (1400 °C). That is the hottest part of the flame. The color inside the flame becomes yellow, orange, and finally red.',
  'Kiss is an American hard rock band that formed in New York City, USA in 1973. The group has performed and recorded continuously since their formation. KISS has sold over 100 million albums worldwide and has been awarded 45 gold albums to date, and has certified sales of 19 million records in the U.S.',
  'March 22, 1995: Longest Human Space Adventure Ends. 1995: Cosmonaut Valeri Polyakov returns to Earth from the longest-ever stay in space by a human. He spent just over 437 days in the Mir space station.',
  'Let\'s compare the dwarf planet Pluto and Mercury. In terms of size, scientists now know that Mercury is significantly larger than Pluto. The diameter of Mercury is 4,879.4 km across, while Pluto\'s diameter is 2,360 km across.',
  'The largest internal organ is the liver. It is also the heaviest organ, with an average of 1.6 kilograms (3.5 pounds). The largest external organ, which is also the largest organ in general, is the skin.',
  'When a male penguin falls in love with female penguin, he searches the entire beach to find the perfect pebble to present to her.',
  'New Zealand will deny people residency visa’s if they too high of a BMI and there are cases where people have been rejected because of their weight.',
  'Whenever a pregnant women suffers from organ damage like heart attack, the fetus sends stem cells to the organ helping it to repair.',
  'It is illegal to climb trees in Oshawa, a town in Ontario, Canada.',
  'Brown eyes are blue underneath, and you can actually get a surgery to turn brown eyes blue.',
  'When you blush, the lining of your stomach also turns red.',
  'A bolt of lightning is six times hotter than the sun.',
  'When a person cries and the first drop of tears come from the right eye, its happiness. if it from left eye, it’s pain.',
  'Only 2% of Earth population naturally has green eyes.',
  'Having bridesmaids in a wedding wasn’t originally for moral support. They were intended to confuse evil spirits or those who wished to harm the bride.',
  'Crying makes you feel better, reduce stress, and may help to keep the body healthy.',
  'Mount Everest is pronounced as Eve-rest, not Ever-est , as it is named after George Everest.',
  'All pandas in the world are on loan from China.',
  'When howling together, no two wolves will howl on the same note, instead, they harmonize to create the illusion that there are more of them than there actually are.',
  'Your nose can remember 50,000 different scents.',
  'India’s “Go Air” airline only hires female flight attendants because they are lighter, so they save up to US$500,000 per year in fuel.',
  'At room temperature, the average air molecule travels at the speed of a rifle bullet.',
  'The most common color for highlighters is yellow because it doesn’t leave a shadow on the page when photocopied.',
  'The Bermuda Triangle has as many ship and plane disappearances as any other region of the ocean.',
  'Dolphins recognize and admire themselves in mirrors.',
  'After working out, it takes 5 hours for your body temperature to return to normal.',
  'Children have more taste buds than adults.',
  'The eye makes movements 50 times every second.',
  'An ant’s sense of smell is stronger than a dog’s.',
  'A day on Venus lasts longer than a year, it is 243 Earth days.',
  'A snail breathes through its foot.',
  'Polar bear fur is transparent, not white.',
  'Cat kidneys are so efficient they can rehydrate by drinking seawater.',
  'During a car crash, 40 % of drivers never even hit the brakes.',
  'When the moon is directly overhead, you weigh slightly less.',
  'Sitting straight up is bad for your back. You should slough at an angle of 135 degrees.',
  'Honeybees navigate by using the sun as a compass.',
  'Strawberries contain more vitamin C than oranges.',
  'Banana milkshake is the perfect cure for hangover.',
  '90% of U.S. media(TV, news, radio) is owned by 6 companies.',
  'Goldfish don’t have stomachs.',
  'Melting ice and icebergs make frizzing noise called “bergy selter”.',
  'Some tumors can grow hair, bones and teeth.',
  'Taking a quick nap after learning can help strengthen your memory.',
  'Having friends from other cultures makes you more creative, study found.',
  'Cherries can cause cancer cells to kill themselves.',
  'Cracking knuckles does not hurt your bones or cause arthritis, the sound you hear is gas bubbles bursting.',
  'Shark pregnancies last up to 4 years.',
  'A full moon is nine times brighter than a half moon.',
  'Smiling actually boosts your immune system.',
  'Dogs and elephants are the only animals that understand pointing.',
  'The main exporter of Brazil nuts is not Brazil. It’s Bolivia.',
  'At rest, your brain one fifth of a calorie per minute.',
  'A single tree can absorb more than 10 pounds of CO2 each year.',
  'Amazon River once flowed in the opposite direction, from east to west.',
  'Bald eagles are so named because balde is an old English word meaning white.',
  'The Amazon River discharges 5 times as much water as any other river on the planet.',
  'Mount Everest shrank one inch or 2.5 cm due to the 2015 earthquake in Nepal.',
  'Lemons are more acidic than vinegar.',
  'A koi fish named Hanoko lived for 225 years.',
  'Caterpillars have about four thousand muscles.',
  'Almost a third of the worlds languages are spoken only in Africa.',
  'The longest jellyfish on record measured 160 feet, more than half the length of a football field.',
  'Giraffe are already extinct in at least seven countries in Africa.',
  'In the U.S., if you find a bald eagle feather on the ground, you need a permit to pick it up.',
  'The Mona Lisa has no eyebrows.',
  'The birthrate for twins has increased 76% since 1980.',
  'The word Anaconda originated from Tamil, ani-kondra meaning elephant killer.',
  'Air pollution in China increases snowfall in California.',
  '63 earths can fit inside Uranus.',
  'Tomatoes came from America and weren’t introduced in Italy until the 1540s.',
  'You can start a fire with ice.',
  'The first color photograph was taken in 1861.',
  'Coffee beans aren’t beans they are seed of coffee berries.',
  'New Zealand is part of Zelandie continent, of which, 93% is submerged.',
  'The oil in cashews helps prevent tooth decay.',
  'The first president of Zimbabwe was president Banana.',
  'The name for the space between eyebrows is “nasion”.',
  'A pineapple is neither an apple nor a pine. It is, in fact, a large berry.',
  'The sun evaporates about a trillion tons of water a day.',
  'Shrimp can only swim backwards.',
  'Mangoes are the most-consumed fruit in the world.',
  'Canada has the longest coastline of any country in the world.',
  'Fresh cranberries can be bounced like a rubber ball.',
  'Broccoli is the only vegetable that is also a flower.',
  'The only lizard that has a voice is the Gecko.',
  'Antarctica is the only continent with no owls.',
  'In Germany, the shhh sound literally means hurry up.',
  'Dogs can make about 10 sounds, while cats make about 100.',
  '75% of people wash from top to bottom in the shower.',
  'Kangaroos can’t walk backwards.',
  'Frogs cannot swallow with their eyes open.',
  'Humans share 50% of their DNA with bananas.',
  'There are approximately 9,000 taste buds on your tongue.',
  'Grapes are the most popular fruit in the world.',
  'The original recipe for chocolate contained chili powder instead of sugar.',
  'Africa is divided into more countries than any other continent.',
  'A cat’s lower jaw cannot move sideways.',
  'Holland is the only country with a national dog.',
  'On average, a laptop uses half as much energy as a desktop computer.',
  'Fish can drown.',
  'Forty is the only number whose letters are in alphabetical order.',
  'Squirrels lose more than half of the nuts they hide.',
  'The human brain is about 80% water.',
  'Jupiter spins so fast that there is a new sunrise nearly every 10 hours.',
  'Banging your head against a wall burns 150 calories an hour.',
  'In the UK, it is illegal to eat mince pies on Christmas Day!',
  'Pteronophobia is the fear of being tickled by feathers!',
  'When hippos are upset, their sweat turns red.',
  'A flock of crows is known as a murder.',
  '“Facebook Addiction Disorder” is a mental disorder identified by Psychologists.',
  'The average woman uses her height in lipstick every 5 years.',
  '29th May is officially “Put a Pillow on Your Fridge Day“.',
  'Cherophobia is the fear of fun.',
  'Human saliva has a boiling point three times that of regular water.',
  'If you lift a kangaroo’s tail off the ground it can’t hop.',
  'Hyphephilia are people who get aroused by touching fabrics.',
  'Billy goats urinate on their own heads to smell more attractive to females.',
  'The person who invented the Frisbee was cremated and made into frisbees after he died!',
  'During your lifetime, you will produce enough saliva to fill two swimming pools.',
  'King Henry VIII slept with a gigantic axe beside him.',
  'An eagle can kill a young deer and fly away with it.',
  'Heart attacks are more likely to happen on a Monday.',
  'If you consistently fart for 6 years & 9 months, enough gas is produced to create the energy of an atomic bomb!',
  'An average person’s yearly fast food intake will contain 12 pubic hairs.',
  'The top six foods that make your fart are beans, corn, bell peppers, cauliflower, cabbage and milk!',
  'There is a species of spider called the Hobo Spider',
  'A toaster uses almost half as much energy as a full-sized oven.',
  'A baby spider is called a spiderling.',
  'You cannot snore and dream at the same time.',
  'The following can be read forward and backwards: Do geese see God?',
  'A baby octopus is about the size of a flea when it is born.',
  'A sheep, a duck and a rooster were the first passengers in a hot air balloon.',
  'In Uganda, 50% of the population is under 15 years of age.',
  'Hitler’s mother considered abortion but the doctor persuaded her to keep the baby.',
  'Arab women can initiate a divorce if their husbands don’t pour coffee for them.',
  'Recycling one glass jar saves enough energy to watch TV for 3 hours.',
  'Smearing a small amount of dog feces on an insect bite will relieve the itching and swelling.',
  'Catfish are the only animals that naturally have an odd number of whiskers.',
  'Facebook, Skype and Twitter are all banned in China.',
  '95% of people text things they could never say in person.',
  'The Titanic was the first ship to use the SOS signal.',
  'About 8,000 Americans are injured by musical instruments each year.',
  'The French language has seventeen different words for ‘surrender’.',
  'Nearly three percent of the ice in Antarctic glaciers is penguin urine.',
  'Bob Dylan’s real name is Robert Zimmerman.',
  'A crocodile can’t poke its tongue out.',
  'Sea otters hold hands when they sleep so they don’t drift away from each other.',
  'A small child could swim through the veins of a blue whale.',
  'Bin Laden’s death was announced on 1st May 2011. Hitler’s death was announced on 1st May 1945.',
  'J.K. Rowling chose the unusual name ‘Hermione’ so young girls wouldn’t be teased for being nerdy!',
  'Hewlett-Packard’s name was decided in a coin toss.',
  'The total number of steps in the Eiffel Tower are 1665.',
  'The Pokémon Hitmonlee and Hitmonchan are based off of Bruce Lee and Jackie Chan.',
  'The toothpaste ‘Colgate’ in Spanish translates to ‘go hang yourself’.',
  'Pirates wore earrings because they believed it improved their eyesight.',
  'In England, in the 1880’s, “Pants” was considered a dirty word.',
  'It snowed in the Sahara desert for 30 minutes on the 18th February 1979.',
  'Every human spent about half an hour as a single cell.',
  'The first alarm clock could only ring at 4am.',
  'Birds don’t urinate.',
  'Dying is illegal in the Houses of Parliaments – This has been voted as the most ridiculous law by the British citizens.',
  'The 20th of March is known as Snowman Burning Day!',
  'Slugs have 4 noses.',
  'Panphobia is the fear of everything… which is a pretty unlucky phobia to have.',
  'An apple, potato, and onion all taste the same if you eat them with your nose plugged.',
  'A company in Taiwan makes dinnerware out of wheat, so you can eat your plate!',
  'The average person walks the equivalent of twice around the world in a lifetime.',
  'The Bible is the most shoplifted book in the world.',
  'Mel Blanc – the voice of Bugs Bunny – was allergic to carrots.',
  'California has issued 6 drivers licenses to people named Jesus Christ.',
  'According to Genesis 1:20-22 the chicken came before the egg.',
  'In the Caribbean there are oysters that can climb trees.',
  'Worms eat their own poo.',
  'Squirrels forget where they hide about half of their nuts.',
  'Over 1000 birds a year die from smashing into windows.',
  'The inventor of the Waffle Iron did not like waffles.',
  'George W. Bush was once a cheerleader.',
  'In 1895 Hampshire police handed out the first ever speeding ticket, fining a man for doing 6mph!',
  'Each year, there are more than 40,000 toilet related injuries in the United States.',
  'Every year more than 2500 left-handed people are killed from using right-handed products.',
  'Madonna suffers from garophobia which is the fear of thunder.',
  'China has more English speakers than the United States.',
  'Samuel L. Jackson requested to have a purple light saber in Star Wars in order for him to accept the part as Mace Windu.',
  'Paraskavedekatriaphobia is the fear of Friday the 13th!',
  'Kleenex tissues were originally used as filters in gas masks.',
  'In 1998, Sony accidentally sold 700,000 camcorders that had the technology to see through people’s clothes. These cameras had special lenses that use infrared light, which allowed you to see through some types of clothing.',
  'Ronald McDonald is “Donald McDonald” in Japan because it makes pronunciation easier for the Japanese. In Singapore he’s known as “Uncle McDonald”.'
];

exports.handler = function(event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.APP_ID = APP_ID;
    alexa.registerHandlers(handlers);
    alexa.execute();
};

var handlers = {
    'LaunchRequest': function () {
        this.emit('GetFact');
    },
    'GetNewFactIntent': function () {
        this.emit('GetFact');
    },
    'GetFact': function () {
        // Get a random random fact from the random facts list
        var factIndex = Math.floor(Math.random() * FACTS.length);
        var randomFact = FACTS[factIndex];

        // Create speech output
        var speechOutput = "Here's your fact: " + randomFact;

        this.emit(':tellWithCard', speechOutput, SKILL_NAME, randomFact)
    },
    'AMAZON.HelpIntent': function () {
        var speechOutput = "You can say tell me a random fact, or, you can say exit... What can I help you with?";
        var reprompt = "What can I help you with?";
        this.emit(':ask', speechOutput, reprompt);
    },
    'AMAZON.CancelIntent': function () {
        this.emit(':tell', 'Goodbye!');
    },
    'AMAZON.StopIntent': function () {
        this.emit(':tell', 'Goodbye!');
    }
};
